-- SQL Subqueries vs JOINs Unveiled
-- SQL Subqueries vs JOINs
-- Generated by WSDA Lesson Generator

-- [query_1] Query 1
SELECT c.category_name, SUM(s.total_sales) AS total_sales FROM (SELECT p.category_id, p.product_id, SUM(s.quantity * p.price) AS total_sales FROM sales s JOIN products p ON s.product_id = p.product_id GROUP BY p.category_id, p.product_id) s JOIN categories c ON s.category_id = c.category_id GROUP BY c.category_name;;

-- [query_2] Query 2
SELECT c.category_name, SUM(s.quantity * p.price) AS total_sales FROM sales s JOIN products p ON s.product_id = p.product_id JOIN categories c ON p.category_id = c.category_id GROUP BY c.category_name;;

-- [query_3] Query 3
SELECT c.category_name, SUM(s.total_sales) AS total_sales FROM (SELECT p.category_id, SUM(s.quantity * p.price) AS total_sales FROM sales s JOIN products p ON s.product_id = p.product_id GROUP BY p.category_id) s JOIN categories c ON s.category_id = c.category_id GROUP BY c.category_name;;
