#!/usr/bin/env python3
"""
WSDA Lesson Generator — AI-powered lesson creation

Usage:
    python3 generate.py --topic "SQL JOINs" --course sql-fundamentals --lesson 3
"""

import asyncio
import json
import os
import re
from pathlib import Path
from typing import Optional

try:
    import openai
    HAS_OPENAI = True
except ImportError:
    HAS_OPENAI = False

from generator.db_builder import DBBuilder
from generator.prompts import CONCEPT_DESIGN, SCHEMA_DESIGN, NARRATION_SCRIPT


class LessonGenerator:
    """Generates complete WSDA lesson packages from a topic string."""

    def __init__(self, model: str = "gpt-4o", api_key: Optional[str] = None):
        self.model = model
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY", "")
        if not self.api_key:
            raise RuntimeError("OPENAI_API_KEY required. Set env var or pass api_key.")
        self.client = openai.AsyncOpenAI(api_key=self.api_key)

    async def _chat(self, prompt: str, temperature: float = 0.7) -> str:
        """Send prompt to OpenAI and return response text."""
        resp = await self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=temperature,
            max_tokens=4000
        )
        return resp.choices[0].message.content

    def _extract_json(self, text: str) -> dict:
        """Extract JSON from AI response (handles markdown code blocks)."""
        # Try fenced code block first
        m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
        if m:
            return json.loads(m.group(1))
        # Try array in code block
        m = re.search(r"```(?:json)?\s*(\[.*?\])\s*```", text, re.DOTALL)
        if m:
            return json.loads(m.group(1))
        # Try raw JSON object
        m = re.search(r"(\{.*\})", text, re.DOTALL)
        if m:
            return json.loads(m.group(1))
        # Try raw JSON array
        m = re.search(r"(\[.*\])", text, re.DOTALL)
        if m:
            return json.loads(m.group(1))
        raise ValueError("No JSON found in response")

    async def generate(self, topic: str, course_id: str, lesson_num: int,
                       output_dir: Path) -> dict:
        """
        Full lesson generation pipeline.
        Returns paths to all generated files.
        """
        print(f"\n{'='*60}")
        print(f"WSDA Lesson Generator")
        print(f"Topic: {topic}")
        print(f"Course: {course_id} | Lesson: {lesson_num}")
        print(f"{'='*60}\n")

        lesson_dir = output_dir / course_id / f"video_{lesson_num}_{lesson_num:02d}"
        assets_dir = lesson_dir / "assets"
        assets_dir.mkdir(parents=True, exist_ok=True)

        # ── Step 1: Concept Design ──
        print("[1/4] Designing lesson concept...")
        concept_prompt = CONCEPT_DESIGN.format(
            topic=topic,
            course_id=course_id,
            lesson_num=lesson_num
        )
        concept_text = await self._chat(concept_prompt, temperature=0.8)
        concept = self._extract_json(concept_text)
        print(f"  Title: {concept.get('title')}")
        print(f"  Hook: {concept.get('hook')}")

        # ── Step 2: Schema + Data + Queries ──
        print("\n[2/4] Building database and queries...")
        schema_prompt = SCHEMA_DESIGN.format(concept_json=json.dumps(concept, indent=2))
        schema_text = await self._chat(schema_prompt, temperature=0.5)
        schema = self._extract_json(schema_text)

        # Build DB
        db_path = assets_dir / f"{course_id}.db"
        builder = DBBuilder(db_path)
        builder.build(
            schema.get("create_statements", []),
            schema.get("insert_statements", [])
        )

        # Verify queries
        verified = builder.verify_queries(schema.get("verified_queries", []))

        # ── Step 3: Write SQL file ──
        print("\n[3/4] Writing SQL file...")
        sql_path = assets_dir / "queries.sql"
        sql_lines = [
            f"-- {concept.get('title', 'Lesson')}",
            f"-- {concept.get('concept', '')}",
            "-- Generated by WSDA Lesson Generator",
            ""
        ]
        for q in verified:
            sql_lines.append(f"-- [{q['ref']}] {q['ref'].replace('_', ' ').title()}")
            sql_lines.append(q["sql"] + ";")
            sql_lines.append("")
        sql_path.write_text("\n".join(sql_lines))
        print(f"  Saved: {sql_path}")

        # ── Step 4: Write Production Card ──
        print("\n[4/4] Writing production card...")

        # Build events from concept + verified queries (deterministic, not AI)
        events = self._build_events(concept, verified, db_path.name, sql_path.name)

        # Try AI narration for better quality, fallback to deterministic
        try:
            narration_prompt = NARRATION_SCRIPT.format(
                concept_json=json.dumps(concept, indent=2),
                query_results_json=json.dumps(verified, indent=2)
            )
            narration_text = await self._chat(narration_prompt, temperature=0.7)
            ai_events = self._parse_ai_events(narration_text, verified, db_path.name, sql_path.name)
            if len(ai_events) > 3:  # Only use AI if it produced real events
                events = ai_events
                print(f"  AI narration: {len(events)} events")
            else:
                print(f"  AI narration failed, using template: {len(events)} events")
        except Exception as e:
            print(f"  AI narration error ({e}), using template: {len(events)} events")

        production_card = {
            "lesson_id": concept.get("lesson_id", f"{course_id}-{lesson_num:02d}"),
            "title": concept.get("title", topic),
            "course_id": course_id,
            "lesson_num": lesson_num,
            "concept": concept.get("concept", ""),
            "events": events
        }

        import yaml
        card_path = lesson_dir / "production_card.yml"
        card_path.write_text(yaml.dump(production_card, sort_keys=False, allow_unicode=True))
        print(f"  Saved: {card_path}")

        print(f"\n{'='*60}")
        print(f"Done! Lesson package ready at:")
        print(f"  {lesson_dir}")
        print(f"{'='*60}\n")

        return {
            "lesson_dir": lesson_dir,
            "production_card": card_path,
            "db_path": db_path,
            "sql_path": sql_path,
            "events": len(events)
        }

    def _build_events(self, concept: dict, verified: list, db_name: str, sql_name: str) -> list:
        """Build a deterministic event sequence from concept and query results."""
        events = []
        eid = 1

        def add(evt_type: str, narr: str = "", **kwargs):
            nonlocal eid
            evt = {"id": f"e{eid:02d}", "type": evt_type, "narration": narr}
            evt.update(kwargs)
            events.append(evt)
            eid += 1
            # Add pause after most events
            if evt_type not in ("show_title_card", "hide_title_card", "fade_out", "pause"):
                events.append({"id": f"e{eid:02d}_pause", "type": "pause", "narration": "", "duration": 1.0})
                eid += 1

        # Title card
        add("show_title_card",
            concept.get("hook", ""),
            badge="SQL Lesson",
            headline=concept.get("title", ""),
            sub=concept.get("concept", ""),
            stakes=concept.get("stakes", ""))
        add("hide_title_card", "")

        # Open database
        add("open_database",
            f"Welcome to the {concept.get('title', 'database')}. We have {len(concept.get('table_descriptions', []))} tables.",
            asset=f"assets/{db_name}")

        # Show schema
        add("show_schema",
            "Take a look at these tables. Each one holds the same data, organized differently.")

        # Load SQL file
        add("open_file",
            "I'm going to run the same question three times, on three different tables.",
            asset=f"assets/{sql_name}")

        # Run each query
        for i, q in enumerate(verified):
            ref = q["ref"]
            name = q.get("name", ref.replace("_", " ").title())

            # Highlight query
            add("highlight_section",
                f"Here's {name}. {q.get('approach', 'This query uses a different approach.')}",
                section=ref)

            # Run query
            add("run_query",
                "Let's run it and see what we get...",
                query_ref=ref,
                columns=q.get("columns", []),
                rows=q.get("rows", []))

            # Show result
            row_count = len(q.get("rows", []))
            add("show_result",
                f"{row_count} rows returned. {q.get('insight', 'Notice the difference.')}")

            # Clear before next (except last)
            if i < len(verified) - 1:
                add("clear_highlights", "")

        # Compare all three
        add("set_layout",
            "Now let me show you all three results at the same time.",
            mode="compare")

        add("compare_results",
            "Three queries. Three different answers. One question.",
            targets=[q["ref"] for q in verified])

        # Zoom and takeaway
        add("zoom_results",
            "Your job as a data practitioner is to know WHICH table to use WHEN.")

        # Fade out
        add("fade_out",
            concept.get("takeaway", "Always check your source table before trusting your numbers."))

        return events

    def _parse_ai_events(self, text: str, verified: list, db_name: str, sql_name: str) -> list:
        """Parse AI-generated events from text."""
        try:
            data = self._extract_json(text)
            if isinstance(data, list):
                events = data
            elif isinstance(data, dict):
                events = data.get("events", [])
            else:
                events = []

            # Inject file references and query results
            for event in events:
                if event.get("type") == "open_database":
                    event["asset"] = f"assets/{db_name}"
                if event.get("type") == "open_file":
                    event["asset"] = f"assets/{sql_name}"
                if event.get("type") == "run_query":
                    ref = event.get("query_ref", "")
                    for v in verified:
                        if v["ref"] == ref:
                            event["columns"] = v["columns"]
                            event["rows"] = v["rows"]
                            break
            return events
        except Exception as e:
            print(f"  [parse] Failed to parse AI events: {e}")
            return []
