-- Decoding COUNT vs SUM Traps
-- Understanding the differences between COUNT and SUM in SQL
-- Generated by WSDA Lesson Generator

-- [query_1] Query 1
SELECT product_id, COUNT(*) AS product_count FROM sales GROUP BY product_id;;

-- [query_2] Query 2
SELECT SUM(quantity) AS total_quantity_sold FROM sales;;

-- [query_3] Query 3
SELECT p.category, COUNT(DISTINCT s.product_id) AS unique_products_sold, SUM(s.quantity) AS total_quantity_sold FROM sales s JOIN products p ON s.product_id = p.product_id GROUP BY p.category;;
